version: '3.9'

services:

    # ------------------------------- Elasticsearch ------------------------------ #
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms2g -Xmx2g
            - cluster.routing.allocation.disk.threshold_enabled=false
            - xpack.security.enabled=true
            - xpack.security.authc.api_key.enabled=true
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./backup/elasticsearch:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"

    # ---------------------------------- Fluentd --------------------------------- #
    fluentd:
        build:
            context: ./fluentd
            dockerfile: Dockerfile
        image: kasra-fluentd
        container_name: fluentd
        volumes:
            - ./fluentd/conf:/fluentd/etc
            - ./fluentd/log:/fluentd/log
        ports:
            - "24224:24224"
            - "24224:24224/udp"
            - "8888:8888"
        restart: unless-stopped
        links:
            - elasticsearch
        depends_on:
            - elasticsearch

    # ---------------------------------- Kibana ---------------------------------- #
    kibana:
        image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
        container_name: kibana
        ports:
            - "5601:5601"
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - XPACK_SECURITY_ENABLED="true"
            - ELASTICSEARCH_USERNAME=${USER_NAME}
            - ELASTICSEARCH_PASSWORD=${PASSWORD}
        depends_on:
            - elasticsearch

    # -------------------------------- APM Server -------------------------------- #
    apm-server:
        image: docker.elastic.co/apm/apm-server:${STACK_VERSION}
        container_name: apm-server
        environment:
            - output.elasticsearch.hosts=["http://elasticsearch:9200"]
            - setup.kibana.host=http://kibana:5601
            - output.elasticsearch.username=${USER_NAME}
            - output.elasticsearch.password=${PASSWORD}
            - setup.kibana.username=${USER_NAME}
            - setup.kibana.password=${PASSWORD}
        ports:
            - "8200:8200"
        depends_on:
            - elasticsearch
            - kibana

    # ------------------------------- Fleet Server ------------------------------- #
    fleet-server:
        image: docker.elastic.co/beats/elastic-agent:${STACK_VERSION}
        container_name: fleet-server
        environment:
            - FLEET_SERVER_ENABLE=1
            - FLEET_SERVER_ELASTICSEARCH_HOST=http://elasticsearch:9200
            - FLEET_SERVER_SERVICE_TOKEN=${FLEET_SERVER_SERVICE_TOKEN}
            - KIBANA_HOST=http://kibana:5601
        ports:
            - "8220:8220"
        depends_on:
            - elasticsearch
            - kibana
